name: CI-CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 539358810919
      S3_SBOM_BUCKET: sbom-storage-bucket

    steps:
      - uses: actions/checkout@v3

      - name: Scannig the repository with Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --report-format json --report-path gitleaks-report.json

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo docker system prune -af || true
          sudo rm -rf /tmp/* || true

      - name: Configure Trivy dirs
        run: |
          mkdir -p $HOME/.cache/trivy
          echo "TRIVY_CACHE_DIR=$HOME/.cache/trivy" >> $GITHUB_ENV
          echo "TMPDIR=$HOME" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - uses: aws-actions/amazon-ecr-login@v2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Prepare Cosign key
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - name: Build Gateway Image
        run: docker build -t gateway_image ./gateway

      - name: Push Gateway Image
        run: |
          docker tag gateway_image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest
          docker rmi gateway_image
      
      - name: Sign gateway image
        run: cosign sign --key cosign.key $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest

      - name: Build LLM Image
        run: docker build -t llm_image ./llm

      - name: Push LLM Image
        run: |
          docker tag llm_image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/llm:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/llm:latest
          docker rmi llm_image
      
      - name: Sign llm image
        run: cosign sign --key cosign.key $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/llm:latest

      - name: Build Storage Image
        run: docker build -t storage_image ./storage

      - name: Push Storage Image
        run: |
          docker tag storage_image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/storage:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/storage:latest
          docker rmi storage_image
      
      - name: Sign storage image
        run: cosign sign --key cosign.key $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/storage:latest

      - uses: aquasecurity/trivy-action@master
        name: Trivy Scan Gateway
        with:
          image-ref: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gateway:latest
          severity: HIGH,CRITICAL
          exit-code: '0'

      - uses: aquasecurity/trivy-action@master
        name: Trivy Scan LLM
        with:
          image-ref: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/llm:latest
          severity: HIGH,CRITICAL
          exit-code: '0'

      - uses: aquasecurity/trivy-action@master
        name: Trivy Scan Storage
        with:
          image-ref: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/storage:latest
          severity: HIGH,CRITICAL
          exit-code: '0'

      - uses: anchore/sbom-action@v0
        name: Generate SBOM - Gateway
        with:
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gateway:latest
          output-file: gateway_sbom.json

      - uses: anchore/sbom-action@v0
        name: Generate SBOM - LLM
        with:
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/llm:latest
          output-file: llm_sbom.json

      - uses: anchore/sbom-action@v0
        name: Generate SBOM - Storage
        with:
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/storage:latest
          output-file: storage_sbom.json

      - name: Upload SBOMs to S3
        run: |
          aws s3 cp gateway_sbom.json s3://$S3_SBOM_BUCKET/sbom/gateway_sbom.json
          aws s3 cp llm_sbom.json s3://$S3_SBOM_BUCKET/sbom/llm_sbom.json
          aws s3 cp storage_sbom.json s3://$S3_SBOM_BUCKET/sbom/storage_sbom.json

      - name: Cleanup Cosign key
        run: rm -f cosign.key
